In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
import tensorflow as tf
import numpy as np
SAVE_PATH = "/content/gdrive/My Drive/canor_model_predb32/log"
checkpoint = tf.train.latest_checkpoint(SAVE_PATH)
print(checkpoint)

/content/gdrive/My Drive/canor_model_predb32/log/model.ckpt-53200


In [0]:
#my model pred
#read data
X=np.load('/content/gdrive/My Drive/test_demo/samples.npy')





In [0]:
#Read graph
with tf.gfile.GFile("/content/gdrive/My Drive/canor_model_predb32/graph/graph.pb","rb")as f:
  graph_def = tf.GraphDef()
  graph_def.ParseFromString(f.read())


In [5]:
#load weights
#with tf.Session() as sess:
  sess= tf.Session()
  saver=tf.train.import_meta_graph(checkpoint + '.meta')
  saver.restore(sess,tf.train.latest_checkpoint(SAVE_PATH))
  graph = tf.get_default_graph()
  



Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /content/gdrive/My Drive/canor_model_predb32/log/model.ckpt-53200


In [0]:
x = graph.get_tensor_by_name("input:0")
dropout =  graph.get_tensor_by_name("dropout:0")
eval_pred = graph.get_tensor_by_name("prediction:0")

In [0]:
#!tensorboard --inspect --event_file=events.out

#!tensorboard --inspect --event_file=myevents.out

In [8]:
#testing
x_raw = X

#prediction
pred = sess.run(eval_pred,feed_dict={x:x_raw,dropout:1.0})
indices = np.argsort(pred)[0][::-1]
print(indices)
#print (list(LABEL)[indices[0]])


[4 3 6 9 2 0 5 7 8 1]


model 3

100 - [8 9 0 3 5 6 1 4 7 2]

200- [3 9 8 0 5 4 6 1 7 2]

300 -[3 9 8 0 4 7 5 6 1 2]

model 2

100 - [3 0 8 9 6 5 4 1 2 7]

200 - [3 8 0 9 4 6 5 7 1 2]

300 - [3 0 8 9 4 6 5 7 2 1]

400-  [3 0 8 9 4 7 6 5 2 1]

model 1

[0 9 8 3 5 6 1 4 7 2] -100

[3 9 8 0 5 4 6 7 2 1] - 200

[3 9 4 8 0 6 2 7 5 1] - 300
